name: xpenseappstate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_slidable: ^1.3.0
  flutter_typeahead: ^4.0.0
  get: 4.6.5
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  
  
  shared_preferences: ^2.0.15
  url_launcher: 6.1.0
  rxdart: ^0.27.3
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^9.5.3+1

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: 2.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
flutter_test:
  sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/images/xpenselogo.png
    - assets/images/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/font/MyFlutterApp.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
